# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160921_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
